version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: saturday
      time: "09:00"
    target-branch: newest
    groups:
      github_action-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: saturday
      time: "09:00"
    target-branch: stable