version: '2'

volumes:
  unbound.conf.d:

services:
  unbound:
    container_name: unbound
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/lizenzfass78851/docker-unbound:latest
    hostname: unbound
    ports:
      - 5335:5335/tcp
      - 5335:5335/udp
    volumes:
      - unbound.conf.d:/etc/unbound/unbound.conf.d:ro
    restart: unless-stopped
