version: '2'

services:
  pihole:
    container_name: unbound
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/lizenzfass78851/docker-unbound:latest
    hostname: unbound
    ports:
      - 5335:5335/tcp
      - 5335:5335/udp
    restart: unless-stopped

